### ISSUE TITLE
Installing on a vanilla based launcher (PojavLauncher)

### ISSUE THREAD

**Issue by Raidenxd2** [GTNewHorizons/lwjgl3ify#50] opened 2023-03-20 22:20 UTC
Is it possible to do this? To me it shouldn't just be limited to MultiMC based launchers.

**Comment by boubou19** [comment] 2023-03-20 22:37
it is possible to make all the mainstream launchers compatible, just not high prio at the moment. But you made me discover PojavLauncher, which is an android launcher to play minecraft java edition, which is way beyond the scope of support i guess. Maybe one day, but mainstream launchers (curseforge and technic) will have priority over this weird configuration

**Comment by eigenraven** [comment] 2023-03-26 11:58
Duplicate of #27 - adding vanilla launcher jsons should be enough to also work with this (and if all else fails, the relauncher could be used). I think I'll do it when lwjgl 3.3.2 finally releases, looks like it should be soon - to avoid having to maintain so many snapshot urls by hand.

**Closed by eigenraven** 2023-03-26 11:58 UTC

**Comment by Raidenxd2** [comment] 2023-03-27 21:21
> Duplicate of #27 - adding vanilla launcher jsons should be enough to also work with this (and if all else fails, the relauncher could be used). I think I'll do it when lwjgl 3.3.2 finally releases, looks like it should be soon - to avoid having to maintain so many snapshot urls by hand.

Ok thanks!
